<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <AssemblyName>Com0ComSharp.Tool</AssemblyName>
    <Version>0.6.0-preview.1</Version>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="../Com0ComSharp/Com0ComSharp.csproj" /></ItemGroup>
</Project>
